### ISSUE TITLE
Got `urllib.error.HTTPError: HTTP Error 403: Forbidden` while downloading the pretrained model for the BERT Base and Huggingface DistilBERT model variant

### ISSUE THREAD

**Issue by JoeyTPChou** [HabanaAI/Model-References#17]
Got forbidden error while downloading pretrained BERT and vocab in this step[ Download the pretrained model for the BERT Base and Huggingface DistilBERT model variant](https://github.com/HabanaAI/Model-References/tree/master/TensorFlow/nlp/distilbert#pre-requisites). Please kindly let me know if there is another source to download them.

The command was executed in a docker container with image `vault.habana.ai/gaudi-docker/1.4.1/ubuntu20.04/habanalabs/tensorflow-installer-tf-cpu-2.7.1`

**Command**
```
$PYTHON download/download_pretrained_model.py \
        "https://storage.googleapis.com/bert_models/2020_02_20/" \
        "uncased_L-12_H-768_A-12" \
        "distilbert-base-uncased" \
        False
```

**Error message**
```
Traceback (most recent call last):
  File "download/download_pretrained_model.py", line 33, in download_pretrained_model_r
    inf = urllib.request.urlopen(pretrained_url + pretrained_model + ".zip")
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download/download_pretrained_model.py", line 102, in <module>
    download_pretrained_model_r(pretrained_url, pretrained_model_bert, flatten_archive)
  File "download/download_pretrained_model.py", line 57, in download_pretrained_model_r
    raise Exception(f"{host_name}: Error in {__file__} download_pretrained_model()") from exc
Exception: 0bc3ecc5bb27: Error in download/download_pretrained_model.py download_pretrained_model()
```

**Comment by greg-serochi** [comment]
HI @JoeyTPChou, we are looking at this.

**Comment by greg-serochi** [comment]
Hi @JoeyTPChou, are you trying to access this thru a proxy?

**Comment by JoeyTPChou** [comment]
Hi Greg, thanks for your reply. I am not sure what you meant. I did it on AWS DL1 inside the `vault.habana.ai/gaudi-docker/1.4.1/ubuntu20.04/habanalabs/tensorflow-installer-tf-cpu-2.7.1 container`

**Comment by JoeyTPChou** [comment]
Hi @hsubramony, sorry for my late reply. I just tried it again and somehow it worked this time ... I will close the issue.
